############################################################
# +------------------------------------------------------+ #
# |                                                      | #
# |              KOTH Plugin Configuration               | #
# |                  Made By Tarj Mecwan                 | #
# |                                                      | #
# +------------------------------------------------------+ #
############################################################

SCOREBOARD:
  USE_SCOREBOARD: true
  UPDATE_TICKS: 20
  SCOREBOARD_TITLE: '&a&lKOTH'
  SCOREBOARD_LINES:
  - '&6&lRunning KOTH(s):'
  - '%koth%'
  - ' '
  - '&6&lTime Remaining:'
  - '%timeleft%'
  - ' '
  - '&6&lLocation:'
  - 'X: %x%'
  - 'Y: %y%'
  - 'Z: %z%'
  - ' '
  - '&6&lControlling:'
  - 'Player(s): %player%'
  - 'Faction(s): %team%'
  DISABLE_IN_WORLD: # Any player in these worlds will not receive scoreboard updates
  - exampleworld
  ONLY_IN_REGION: # If you only want to display the scoreboard in these WorldGuard regions
    ENABLED: false
    REGIONS:
    - example

FEATHERBOARD_TRIGGER: # Make sure KOTH scoreboard is disabled and that the scoreboard name is in the "scoreboards" folder of Featherboard
  ENABLED: true
  SCOREBOARD_NAME: koth
  
REWARDS:
  USE_REWARDS: true
  MAX_LOOT_ITEMS: 5
  MIN_LOOT_ITEMS: 3
  CHEST_SIZE: 27
  VIEW_INVENTORY_NAME: '&cKOTH LOOT' # The real inventory name must be different from the view
  REAL_INVENTORY_NAME: '&aKOTH LOOT' # The real inventory name must be different from the view
  DUPLICATE_LOOT: true
  LEFT_CLICK_SHOW_LOOT: true
  GIVE_TEAM_LEADER: false # Give rewards to faction leader
  GIVE_ALL_MEMBERS: false # Give rewards to all members
  KEY:
    ITEM_MATERIAL: TRIPWIRE_HOOK
    ITEM_DISPLAY_NAME: '&aKOTH Key'
    ITEM_DISPLAY_LORE:
    - '&7This is the default lore.'
    ITEM_AMOUNT: 1
    GLOW: false

PLAYER_COOLDOWN: # Use this to allow players to start KOTH via command but have a cooldown once started
  USE_COOLDOWN: true
  COOLDOWN_TIME: 30

KOTH_TOP:
  ENABLED: true
  SORT_DELAY: 300
  DEFAULT_TYPE: 'TEAM' # Enter PLAYER or TEAM here which will be displayed when players do /koth top without specifying a type

KOTH_STARTER_ITEM:
  START_TIME: 300
  MINIMUM_PLAYERS: 2
  NAME: '&aKOTH Start'
  MATERIAL: EMERALD
  LORE:
  - '&7> Right-click to start the KOTH event.'

KOTH_ADMIN_GUI:
  NAME: '&aKOTH START GUI'
  SIZE: 27

KOTH_PLAYER_GUI:
  NAME: '&aKOTH PLAYER GUI'
  SIZE: 27
  
DISABLE_BROADCASTS_IN_WORLDS: # Disable any KOTH related broadcasts in these worlds
- example  

BROADCAST_PERMISSION: # Enable this to have players require this permission to see messages
  ENABLED: false # Permission is KOTH.MESSAGES

KNOCK_DELAY: 5 # This will prevent the chat from being spammed.

# List of timezones can be found here https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
# Any spaces in a timezone should be used as an "_"

CURRENT_TIMEZONE: Europe/London

VIEW_COMMAND_PER_PERMISSION: false

ANNOUNCE_KOTH_ON_JOIN: true

PERMISSION_FOR_CAPTURE: false

ALLOW_NO_TEAM_CAPTURE: true # Set this to false to disable players without a team to capture

ALLOW_FULL_TEAM_CAPTURE: false # Set this to true to allow a whole team to capture rather than a player

USE_NEW_TIMEFORMAT: false # If this is set to true all time formats will be hh,mm,ss.

PAUSE_OTHER_TEAMS: false # Pause capture if another team is stood on the zone

KEEP_INVENTORY_WHILE_ACTIVE:
  ENABLED: false # Set this to true for all players to keep inventory on death while KOTH is active
  DISABLE_IN_WORLD: # List of worlds this will be enabled in
  - exampleworld
  ONLY_IN_REGION:
   ENABLED: false
   REGIONS:
   - example
  
  
# Set this to true if you want to make the capper time and lose capture to be a priority and not be affected by TPS
# Be warned if you set this to true it could cause more lag on your server

RUN_CAPPER_SYNC: false
  
RESET_MAXRUNTIME_ON_CAPTURE: false # Set this to true to reset the maxruntime every time a player starts capturing

CUSTOM_HELP_PAGE:
  ENABLED: false
  TITLE: '&aCustom KOTH Help Menu'
  PAGES:
    1: # List the page number here
    - '&a/koth times &b- View the scheduled KOTHs.'
    
MINIMUM_PLAYERS_FOR_SCHEDULE_START: -1 # Set to -1 for this to be disabled
 
HOLOGRAM_EVENTS: # Use this feature to reload holograms to update with new cappers etc
  NEW_CAPPER: false
  
BOSS_BAR:
  ENABLED: true
  TEXT: '&aKOTH Percentage Capped'
  
# This feature allows you to set a maximum amount of time allowed of the capture zone before losing control
# Set to -1 to disable this feature, by default it's off so you instantly lose control  
  
DELAYED_PLAYER_LOSE_CAPTURE: -1

# Use this feature to use a point system instead of a timer

KOTH_POINTS_SYSTEM:
  ENABLED: false
  STORED_TYPE: 'PLAYER' # Put either 'PLAYER' or 'TEAM' here
  POINTS_PER_TICK: 1
  

#################################################################
#                                                               #
#                   Forced Team Hook Section                    #
#                                                               #
#  Only use this section if you have multiple team plugins on   #
#                   the supported plugin list                   #
#                                                               #
#################################################################    

# Please type the plugin name you want to force hook

FORCED_HOOK:
  ENABLED: false
  PLUGIN: ''  